### ISSUE TITLE
Run Every hour at a specific time

### ISSUE THREAD

**Issue by hexadecy** [roylee0704/gron#1]
gron.Every(1 \* time.Hour).At("00:30"), func() { 
    fmt.Println("Every hour on the half hour") 
})

crontab:
0 30 \* \* \* *

My use case is that I want to run every hour: 
job1 at 00:30
job2 at 00:40

**Comment by deankarn** [comment]
I have the same need but for every 10 minutes of the hour

0 */10 \* \* \* *

This would allow me to make the switch to gron 👍

**Comment by roylee0704** [comment]
@hexadecy @joeybloggs seems to be a pretty cool feature, I will work it this out :)

**Comment by deankarn** [comment]
if it help it looks like [tinycron](https://github.com/bcicen/tinycron) has this implemented already for some reference.

**Comment by Mrhyuan** [comment]
Hi any news on this feature? Thanks.

**Comment by deankarn** [comment]
So did this get implemented?
